version: "3.9"

services:
  backend:
    env_file:
        - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fund-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - fundnet
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend/fundfolio-api-ui
      dockerfile: Dockerfile
    container_name: fund-frontend
    ports:
      - "3000:3000"
    networks:
      - fundnet
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: fund-redis
    ports:
      - "6379:6379"
    networks:
      - fundnet

networks:
  fundnet:
    driver: bridge
