version: "3.9"

services:
  backend:
    env_file:
        - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fund-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - fundnet

  frontend:
    build:
      context: ./frontend/fundfolio-api-ui
      dockerfile: Dockerfile
    container_name: fund-frontend
    ports:
      - "3000:3000"
    networks:
      - fundnet
    depends_on:
      - backend

networks:
  fundnet:
    driver: bridge
