"""add portfolio tracking fields

Revision ID: 136755d291d8
Revises: d0fdd3d79033
Create Date: 2025-05-16 15:47:49.227378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136755d291d8'
down_revision: Union[str, None] = 'd0fdd3d79033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('purchase_price', sa.Float(), nullable=True))
    op.add_column('portfolios', sa.Column('current_price', sa.Float(), nullable=True))
    op.add_column('portfolios', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'last_updated')
    op.drop_column('portfolios', 'current_price')
    op.drop_column('portfolios', 'purchase_price')
    # ### end Alembic commands ###
